# @File    : compare_two_json
# @Description:
# @Author  : yangbaihua
# @Department:研发部-测试一组
# @Time    : 2020/10/12 9:43

def get_target_value(key, dic, tmp_list):
    """
    :param key: 目标key值
    :param dic: JSON数据
    :param tmp_list: 用于存储获取的数据
    :return: list
    """
    if not isinstance(dic, dict) or not isinstance(tmp_list, list):  # 对传入数据进行格式校验
        return 'argv[1] not an dict or argv[-1] not an list '

    if key in dic.keys():
        tmp_list.append(dic[key])  # 传入数据存在则存入tmp_list
    else:
        for value in dic.values():  # 传入数据不符合则对其value值进行遍历
            if isinstance(value, dict):
                get_target_value(key, value, tmp_list)  # 传入数据的value值是字典，则直接调用自身
            elif isinstance(value, (list, tuple)):
                _get_value(key, value, tmp_list)  # 传入数据的value值是列表或者元组，则调用_get_value
    return tmp_list


def _get_value(key, val, tmp_list):
    for val_ in val:
        if isinstance(val_, dict):
            get_target_value(key, val_, tmp_list)  # 传入数据的value值是字典，则调用get_target_value
        elif isinstance(val_, (list, tuple)):
            _get_value(key, val_, tmp_list)  # 传入数据的value值是列表或者元组，则调用自身

def cmp(key1,key2,src_list,dst_list):
    list1 = dict(zip(get_target_value(key1, src_list, []), get_target_value(key2, src_list, [])))
    list2 = dict(zip(get_target_value(key1, dst_list, []), get_target_value(key2, dst_list, [])))
    for k, v in list1.items():
        if k in list2:
            if list1[k] != list2[k]:
                print('参照列表key值不相等  ' + k, v, list2[k])
            else:
                pass
        else:
            print('参照列表不存在该key：' + k, v)


if __name__ == '__main__':
    # print(DubboClient('zookeeper://zookeeper.szy.com:2181').object2Json('com.ztjy.hms.server.model.dto.OperLogDto'))
    # print(DubboClient('zookeeper://zookeeper.szy.com:2181').object2Json('com.szy.schoolserver.openservice.facade.IRClassFacade'))
    # orderNo='XFJ2020081601WGn3'

    # selectField = {
    #     'school_id': 'testSch1601172866458'
    # }
    # updateField = {
    #     'optype': 'login121212'
    # }
    # OPER_SYS_LOG_DB().update_sales_order_sql(selectField, updateField)

    params1 = {"body": {"downurl": "gw.szytest.com",
                        "identitypelist": [{"sex": "female", "typeid": "MOM", "typename": "妈妈"},
                                           {"sex": "male", "typeid": "DAD", "typename": "爸爸"},
                                           {"sex": "female", "typeid": "NN", "typename": "奶奶"},
                                           {"sex": "male", "typeid": "YY", "typename": "爷爷"},
                                           {"sex": "female", "typeid": "LL", "typename": "外婆"},
                                           {"sex": "male", "typeid": "LY", "typename": "外公"},
                                           {"sex": "female", "typeid": "YM", "typename": "姨妈"},
                                           {"sex": "male", "typeid": "YF", "typename": "姨夫"},
                                           {"sex": "female", "typeid": "GM", "typename": "姑母"},
                                           {"sex": "male", "typeid": "GF", "typename": "姑父"},
                                           {"sex": "male", "typeid": "JJ", "typename": "舅舅"},
                                           {"sex": "female", "typeid": "JM", "typename": "舅母"},
                                           {"sex": "male", "typeid": "SS", "typename": "叔叔"},
                                           {"sex": "female", "typeid": "SHENS", "typename": "婶婶"},
                                           {"sex": "female", "typeid": "JIEJIE", "typename": "姐姐"},
                                           {"sex": "male", "typeid": "GG", "typename": "哥哥"},
                                           {"sex": "male", "typeid": "BF", "typename": "伯父"},
                                           {"sex": "female", "typeid": "BM", "typename": "伯母"},
                                           {"sex": "female", "typeid": "SAOSAO", "typename": "嫂嫂"},
                                           {"sex": "female", "typeid": "OTHER", "typename": "亲友"},
                                           {"sex": "female", "typeid": "CUSTOM", "typename": "其他"}],
                        "uploadtoken": "M7ayQ5wNByNG1sTRyVHU1FJrl2f3njm_LPShfukZ:nqyoZ3udH1Xj_VpKu6lq9gaYuHY=:eyJzY29wZSI6Inp0aG9tZSIsImRlYWRsaW5lIjoxNjAyMzE3Nzg4fQ==",
                        "defaulthomemodule": "jz00001",
                        "sendsmshourslist": [{"smstype": "1", "hoursvalue": "1"}, {"smstype": "3", "hoursvalue": "1"}],
                        "parentlimitbabynum": 100,
                        "urllist": [{"urltype": "detailurl", "url": "https://wx.szy.cn/service/getViewPage.action?"},
                                    {"urltype": "myschoolurl",
                                     "url": "http://wx.szy.cn/H5Server/service/getSchoolInfoPage.action?"},
                                    {"urltype": "helpurl", "url": "http://51110.com/mfaq"}, {"urltype": "coursesurl",
                                                                                             "url": "https://wx.szy.cn/service/getViewCoursePage.action?"},
                                    {"urltype": "recipesurl",
                                     "url": "https://wx.szy.cn/service/getViewFoodPage.action?"},
                                    {"urltype": "songsurl", "url": "http://www.4399er.com/erge/"},
                                    {"urltype": "readingurl", "url": "http://yuer.szy.cn/index_7137D1D9.php"},
                                    {"urltype": "storyurl", "url": "http://www.4399er.com/gushi/"},
                                    {"urltype": "reportrepail", "url": "https://wx.szy.cn/jsp/mobile/weixin.jsp?"},
                                    {"urltype": "detailexerciseteacher",
                                     "url": "http://a.szy.com/MessageServer/page/detailExercise.action?source=app&checksign=0&"},
                                    {"urltype": "detaillexerciseparent",
                                     "url": "http://a.szy.com/MessageServer/page/detailExercise.action?source=app&checksign=0&isGroups=1&"},
                                    {"urltype": "detailnotfyteacher",
                                     "url": "http://a.szy.com/MessageServer/page/detailNotfy.action?source=app&checksign=0&"},
                                    {"urltype": "detaillnotfyparent",
                                     "url": "http://a.szy.com/MessageServer/page/detailNotfy.action?source=app&checksign=0&isGroups=1&"},
                                    {"urltype": "detaillnewparent",
                                     "url": "http://a.szy.com/MessageServer/page/detailNews.action?source=app&checksign=0&"},
                                    {"urltype": "detailnewteacher",
                                     "url": "http://a.szy.com/MessageServer/page/detailNews.action?source=app&checksign=0&"},
                                    {"urltype": "teacherdosagereport",
                                     "url": "http://hms.szy.com/statistics/teacherAction_index.action?"},
                                    {"urltype": "leaderdosagereport",
                                     "url": "http://hms.szy.com/statistics/leaderAction_getylReport.action?"},
                                    {"urltype": "aboutus", "url": "http://wx.szy.cn/H5Server/about/aboutus.action?"},
                                    {"urltype": "weixin_msg",
                                     "url": "http://a.szy.com/MessageServer/page/weiXinMsg.action?"},
                                    {"urltype": "luckpageurl",
                                     "url": "http://wx.szy.cn/H5Server/icdActivity/getTeacherAct?sessionid=E81627DE292B4E8FAF3AEE7A35A39969"},
                                    {"urltype": "myscorepageurl",
                                     "url": "https://wx.szy.cn/service/getMyScorePage.action?"},
                                    {"urltype": "parenttasklistpageurl",
                                     "url": "https://H5Server.szy.com/H5Server/service/getParentAppTaskListPage?"},
                                    {"urltype": "teachertasklistpageurl",
                                     "url": "https://H5Server.szy.com/H5Server/service/getTeacherAppTaskListPage?"},
                                    {"urltype": "levelinfopageurl",
                                     "url": "https://H5Server.szy.com/H5Server/service/getLevelInfoList?"},
                                    {"urltype": "scoredetaillistpageurl",
                                     "url": "https://H5Server.szy.com/H5Server/service/scoreDetailPage?sessionid=E81627DE292B4E8FAF3AEE7A35A39969&teacherid=0efba4b5c852401aa4f9"},
                                    {"urltype": "popularityteacherranking",
                                     "url": "https://H5Server.szy.com/H5Server/rank/getGardenerRankingPage?"},
                                    {"urltype": "popularteacherranking",
                                     "url": "https://H5Server.szy.com/H5Server/rank/getPatriarchRankingPage?"},
                                    {"urltype": "popularitydetailpageurl",
                                     "url": "https://wx.szy.cn/service/getPopularityDetailPage.action?teacherId=0efba4b5c852401aa4f9"},
                                    {"urltype": "affichedetai",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android"},
                                    {"urltype": "afficheweixinshare",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/getAfficheWeixin.action?"},
                                    {"urltype": "previewnotifybyteacher",
                                     "url": "http://a.szy.com/MessageServer/page/previewNotifyByTeacher.action?"},
                                    {"urltype": "parentdownloadurl", "url": "http://t.szy.cn/ztjyjz"},
                                    {"urltype": "teacherdownloadurl", "url": "http://dwz.cn/ztjyydnew"},
                                    {"urltype": "scoretaskdescurl",
                                     "url": "https://H5Server.szy.com/H5Server/service/getTaskHelpPage?schoolId=vE7Z48ptN75viDCtAKX"},
                                    {"urltype": "inviteurl", "url": "https://wx.szy.cn/service/teacherAppDown.action?"},
                                    {"urltype": "h5serverinviteurl",
                                     "url": "https://wx.szy.cn/H5Server/service/teacherAppDown?"},
                                    {"urltype": "coupondetailurl",
                                     "url": "https://testsecurity.ztjy61.cn/SalesPromotionServer/coupon/getCouponDetail.action?"},
                                    {"urltype": "couponreceiveweixinurl",
                                     "url": "https://testsecurity.ztjy61.cn/SalesPromotionServer/coupon/getCouponReceiveWeixin.action?"},
                                    {"urltype": "inviteteacherurl",
                                     "url": "https://wx.szy.cn/invitation/inviteTeacherPage.action?"},
                                    {"urltype": "inviteteacherweixinurl",
                                     "url": "https://wx.szy.cn/invite/inviteTeacherWeiXin.action?"},
                                    {"urltype": "insuranceurl",
                                     "url": "https://wx.szy.cn/activity/showInsuranceStudent.action?"},
                                    {"urltype": "previewnewteacher",
                                     "url": "http://a.szy.com/MessageServer/page/previewNews.action?source=app&checksign=0&"},
                                    {"urltype": "previewactivityteacher",
                                     "url": "http://a.szy.com/MessageServer/page/previewActivity.action?source=app&checksign=0&"},
                                    {"urltype": "educationnoticedetail",
                                     "url": "https://testsecurity.ztjy61.cn/EducationServer/announcement/detail.action?"},
                                    {"urltype": "schoolenrollmenturl",
                                     "url": "http://wx.szy.cn/H5Server/service/getSchoolEnrollmentInfoPage.action?"},
                                    {"urltype": "parentexptasklisturl",
                                     "url": "https://testsecurity.ztjy61.cn/ScoreServer/score/getParentExpTaskListPage.action?sessionid=E81627DE292B4E8FAF3AEE7A35A39969"},
                                    {"urltype": "teacheractiveinviteurl",
                                     "url": "http://wx.szy.cn/H5Server/service/getSchoolInviteTchActivePage.action?"},
                                    {"urltype": "shareteacheractiveinviteurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getSchoolInviteTchActivePage.action?"},
                                    {"urltype": "studentactiveinviteurl",
                                     "url": "http://wx.szy.cn/H5Server/service/getSchoolInviteStuActivePage.action?"},
                                    {"urltype": "sharestudentactiveinviteurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getSchoolInviteStuActivePage.action?"},
                                    {"urltype": "shareschoolbarcodeurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getSchoolQrcodePage.action?"},
                                    {"urltype": "shareclassbarcodeurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getClassQrcodePage.action?"},
                                    {"urltype": "teacherpackageurl",
                                     "url": "http://www.youshikoudai.com/phone/koudai/zhangtongjiayuan"},
                                    {"urltype": "dissolutionpgroupurl",
                                     "url": "http://wx.szy.cn/H5Server/service/getDissolutionPGropPage.action?"},
                                    {"urltype": "sharedissolutionpgroupurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getDissolutionPGropPage.action?"},
                                    {"urltype": "sharemyschoolurl",
                                     "url": "https://wx.szy.cn/H5Server/service/getSchoolInfoPage.action?"},
                                    {"urltype": "shareinformlurl", "url": "http://wx.szy.cn/wxShareDownload?"},
                                    {"urltype": "payreturnurl",
                                     "url": "https://H5Server.szy.com/H5Server/pay/orderResult.action?"},
                                    {"urltype": "shareregisterstudenturl",
                                     "url": "https://wx.szy.cn/H5Server/register/listRegisterStudentCheckPage.action?"},
                                    {"urltype": "citydetailurl",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android"},
                                    {"urltype": "cityweixinshare",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/getAfficheWeixin.action?"},
                                    {"urltype": "citypageurl",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/listPage.action?"},
                                    {"urltype": "affichepageurl",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/listPage.action?"},
                                    {"urltype": "commentdetail",
                                     "url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/commentdetail.action?"},
                                    {"urltype": "contactguide",
                                     "url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/contactguide.action?"},
                                    {"urltype": "growthshareurl",
                                     "url": "http://zthome.ztjystore.cn/BxqENL5kMMwjuTCSx93"},
                                    {"urltype": "growthclassshareurl",
                                     "url": "https://zthome.ztjystore.cn/hoyeAjamHOCvOYMfndx"},
                                    {"urltype": "bindCardExplain",
                                     "url": "https://wx.szy.cn/jsp/mobile/bindCardA.jsp?"},
                                    {"urltype": "shareinviteparenturl",
                                     "url": "https://wx.szy.cn/H5Server/service/getShareInviteParentForward.action?type=5"},
                                    {"urltype": "neardetailurl",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android"},
                                    {"urltype": "nearweixinshare",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/getAfficheWeixin.action?"},
                                    {"urltype": "nearpageurl",
                                     "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/listPage.action?"},
                                    {"urltype": "share2Surrogate",
                                     "url": "https://wx.szy.cn/H5Server/service/getShare2SurrogateForward.action?type=4"},
                                    {"urltype": "userMedalInfo",
                                     "url": "https://wx.szy.cn/medal/getUserMedalInfoPage.action?"},
                                    {"urltype": "improveParentInfo",
                                     "url": "http://wx.szy.cn/H5Server/service/improveParentInfoList.action?source=50&methodVersion=2&schoolId=vE7Z48ptN75viDCtAKX"},
                                    {"urltype": "popularfamilyranking",
                                     "url": "https://H5Server.szy.com/H5Server/rank/getFamilyRankingPage?"},
                                    {"urltype": "leaderreport",
                                     "url": "https://a.szy.com/CalculatorWeb/report/leader/?"},
                                    {"urltype": "teacherreport",
                                     "url": "https://a.szy.com/CalculatorWeb/report/teacher/?"},
                                    {"urltype": "homeworkserver", "url": "http://homework.szy.com:8080/Homework"},
                                    {"urltype": "homeworkpreview",
                                     "url": "http://homework.szy.com:8080/Homework/page/teacher/homework/preview"},
                                    {"urltype": "liveList",
                                     "url": "https://H5Server.szy.com/H5Server/live/user/getUserLiveListPage?sessionId=E81627DE292B4E8FAF3AEE7A35A39969"},
                                    {"urltype": "paysuccessreturnurl",
                                     "url": "https://H5Server.szy.com/H5Server/pay/paySuccessResult.action?"},
                                    {"urltype": "growthdetail",
                                     "url": "https://H5Server.szy.com/H5Server/growth/growthDetail?"},
                                    {"urltype": "recommendurl",
                                     "url": "https://H5Server.szy.com/H5Server/school/reg/recommendIndex?"},
                                    {"urltype": "securitycheckurl",
                                     "url": "https://H5Server.szy.com/H5Server/security/getSecurityCheckPage.action?"},
                                    {"urltype": "securitycheckdetailurl",
                                     "url": "https://H5Server.szy.com/H5Server/security/getSecurityCheckInfoPage.action?"},
                                    {"urltype": "dangersourceurl",
                                     "url": "https://H5Server.szy.com/H5Server/security/getDangerSourcePage.action?"},
                                    {"urltype": "SchoolNotice",
                                     "url": "https://wx.szy.cn/H5Server/service/getSchoolNotifyTeacherActive.action?schoolId=vE7Z48ptN75viDCtAKX&shareUserId=0efba4b5c852401aa4f9&apptype=APP_TYPE_TEACHER"},
                                    {"urltype": "studentUnActiveListPage",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/report/teacher/activestudent?version=6.30.2.1093001"},
                                    {"urltype": "teacherUnActiveListPage",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/report/teacher/activeteacher?"},
                                    {"urltype": "publicSentiment",
                                     "url": "https://H5Server.szy.com/H5Server/publicSentiment/index?"},
                                    {"urltype": "teacherRankList",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/rank/teacherRank.jsp"},
                                    {"urltype": "growthaudioshareurl",
                                     "url": "http://zthome.ztjystore.com/6400010120180813152156621mUk0UjOL"},
                                    {"urltype": "h5SignDetailUrl",
                                     "url": "http://wx.szy.cn/H5Server/view/visitor/visitors/visitor_details.jsp"},
                                    {"urltype": "h5CheckupStatisticsDetailUrl",
                                     "url": "http://wx.szy.cn/H5Server/view/sjinfo/sjinfo.jsp"},
                                    {"urltype": "schoolreport",
                                     "url": "https://a.szy.com/CalculatorWeb/report/school/?"},
                                    {"urltype": "photoRelease",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/photoRelease.jsp"},
                                    {"urltype": "photoReleaseWeek",
                                     "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/photoReleaseWeek?signData=F05B8A506BEB5F467490C430D2A1E283"},
                                    {"urltype": "classDetails",
                                     "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classDetails?signData=F05B8A506BEB5F467490C430D2A1E283"},
                                    {"urltype": "classHuoy",
                                     "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classHuoy?signData=F05B8A506BEB5F467490C430D2A1E283"},
                                    {"urltype": "schoolHuoy",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolHuoy.jsp"},
                                    {"urltype": "schoolHuoyRank",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolHuoyRank.jsp"},
                                    {"urltype": "classHuoyRank",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/classHuoyRank.jsp"},
                                    {"urltype": "schoolUsage",
                                     "url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolUsage.jsp"},
                                    {"urltype": "classDetailsVs",
                                     "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classDetailsVs?signData=F05B8A506BEB5F467490C430D2A1E283"},
                                    {"urltype": "affairsInstructions",
                                     "url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsInstructions.action?"},
                                    {"urltype": "affairsCourse",
                                     "url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsCourse.action?"},
                                    {"urltype": "affairsDetail",
                                     "url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsDetail.action?"},
                                    {"urltype": "albumGuide",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/albumGuide.action"},
                                    {"urltype": "albumKnowMore",
                                     "url": "http://wx.szy.cn/H5Server/view/album/knowMore.jsp"},
                                    {"urltype": "albumAppData",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/albumData.action"},
                                    {"urltype": "classAlbum",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/classAlbumPage.action"},
                                    {"urltype": "studentAlbum",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/studentAlbum.action"},
                                    {"urltype": "shareAlbum",
                                     "url": "https://wx.szy.cn/H5Server/albumPage/shareAlbum.action?verify=43FE66A47535735ADA0B944D677356D6&timeMillis=1602314188049"},
                                    {"urltype": "training", "url": "https://alpha-web.szy.cn/ztjy-training/index"},
                                    {"urltype": "recruit",
                                     "url": "http://ztjy-sales-web.szy.com:9200/productDetail/productDetail?moduleNo=yd0064100"},
                                    {"urltype": "means",
                                     "url": "http://wx.szy.cn/H5Server/means/index.action?moduleNo=yd0081100"},
                                    {"urltype": "cancellationAccountAgreement",
                                     "url": "http://wx.szy.cn/H5Server/view/document/cancellationAgreement.jsp#"},
                                    {"urltype": "drinkWaterInfo",
                                     "url": "http://wx.szy.cn/H5Server/view/healthy/drinkWater.jsp"},
                                    {"urltype": "cancellationAccountAgreement",
                                     "url": "http://wx.szy.cn/H5Server/view/document/cancellationAgreement.jsp#"},
                                    {"urltype": "signPlanRemark",
                                     "url": "http://wx.szy.cn/H5Server/view/sign/signPlanRemark.jsp"},
                                    {"urltype": "albumAppDataV2",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/albumDataV2.action"},
                                    {"urltype": "classAlbumV2",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/classAlbumPageV2.action"},
                                    {"urltype": "schoolAlbumCompletion",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/schoolAlbumCompletion.action"},
                                    {"urltype": "studentAlbumV2",
                                     "url": "http://wx.szy.cn/H5Server/albumPage/studentAlbumV2.action"},
                                    {"url": "https://j.youzan.com/0CNrRY", "urltype": "preferredMall"},
                                    {"url": "https://wx.szy.cn/H5Server/food/getInfoPage?", "urltype": "shareFoodInfo"},
                                    {"url": "http://wx.szy.cn/H5Server/temperature/getNcovCheck?",
                                     "urltype": "temperatureMeasuring"}, {
                                        "url": "http://alpha-web.szy.com/bflive/liveList?sessionId=E81627DE292B4E8FAF3AEE7A35A39969&t=111",
                                        "urltype": "liveZtjyList"},
                                    {"url": "http://wx.szy.cn/H5Server/album/schholPageEdit",
                                     "urltype": "albumSchoolPageEditUrl"},
                                    {"url": "http://alpha-web.szy.com/ztjy-recruit/website/share?",
                                     "urltype": "newMySchoolUrl"},
                                    {"url": "https://alpha-help.szy.cn/allTheList?short_name=czjnc",
                                     "urltype": "albumSchoolPageHelpUrl"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/publishAlbum.action",
                                     "urltype": "publishAlbum"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageAdd.action",
                                     "urltype": "albumPageAdd"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageCategory.action",
                                     "urltype": "albumPageCategory"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageQuanx.action",
                                     "urltype": "albumPageQuanx"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageSet.action",
                                     "urltype": "albumPageSet"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageStyle.action",
                                     "urltype": "albumPageStyle"}, {"urltype": "temperatureCount",
                                                                    "url": "http://ztjy-health-web.szy.com/temperature/collect"},
                                    {"urltype": "temperatureHistory",
                                     "url": "http://ztjy-health-web.szy.com/temperature/record"},
                                    {"urltype": "bluetoothTemperatureDSInterface",
                                     "url": "http://ztjy-health-web.szy.com/temperatureGun.html"},
                                    {"urltype": "bluetoothTemperatureGuide",
                                     "url": "http://ztjy-health-web.szy.com/temperature/connectHelp"},
                                    {"url": "http://alpha-web.szy.com/bflive/bigCoffeeList",
                                     "urltype": "liveAppointmentList"},
                                    {"url": "http://wx.szy.cn/H5Server/albumPage/albumSpineAdd.action",
                                     "urltype": "albumSpineAdd"},
                                    {"url": "http://alpha-web.szy.cn/edge/memberActivated/gardenerActivity",
                                     "urltype": "smileActivityForLeaderUrl"},
                                    {"url": "http://alpha-web.szy.cn/edge/memberActivated/lookActivity",
                                     "urltype": "smileActivityForTeacherUrl"}], "rongappkey": ""}, "message": "成功",
               "returncode": "10000"}

    params2 = {"body": {"downurl": "gw.szytest.com",
                        "identitypelist": [{"sex": "female", "typeid": "MOM", "typename": "妈妈"},
                                           {"sex": "male", "typeid": "DAD", "typename": "爸爸"},
                                           {"sex": "female", "typeid": "NN", "typename": "奶奶"},
                                           {"sex": "male", "typeid": "YY", "typename": "爷爷"},
                                           {"sex": "female", "typeid": "LL", "typename": "外婆"},
                                           {"sex": "male", "typeid": "LY", "typename": "外公"},
                                           {"sex": "female", "typeid": "YM", "typename": "姨妈"},
                                           {"sex": "male", "typeid": "YF", "typename": "姨夫"},
                                           {"sex": "female", "typeid": "GM", "typename": "姑母"},
                                           {"sex": "male", "typeid": "GF", "typename": "姑父"},
                                           {"sex": "male", "typeid": "JJ", "typename": "舅舅"},
                                           {"sex": "female", "typeid": "JM", "typename": "舅母"},
                                           {"sex": "male", "typeid": "SS", "typename": "叔叔"},
                                           {"sex": "female", "typeid": "SHENS", "typename": "婶婶"},
                                           {"sex": "female", "typeid": "JIEJIE", "typename": "姐姐"},
                                           {"sex": "male", "typeid": "GG", "typename": "哥哥"},
                                           {"sex": "male", "typeid": "BF", "typename": "伯父"},
                                           {"sex": "female", "typeid": "BM", "typename": "伯母"},
                                           {"sex": "female", "typeid": "SAOSAO", "typename": "嫂嫂"},
                                           {"sex": "female", "typeid": "OTHER", "typename": "亲友"},
                                           {"sex": "female", "typeid": "CUSTOM", "typename": "其他"}],
                        "uploadtoken": "M7ayQ5wNByNG1sTRyVHU1FJrl2f3njm_LPShfukZ:fXGyHavnpNS481ILpOiOAIVyTcI=:eyJzY29wZSI6Inp0aG9tZSIsImRlYWRsaW5lIjoxNjAyMzE3MjIyfQ==",
                        "defaulthomemodule": "jz00001",
                        "sendsmshourslist": [{"smstype": "1", "hoursvalue": "1"}, {"smstype": "3", "hoursvalue": "1"}],
                        "parentlimitbabynum": 100,
                        "urllist": [
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/report/teacher/activestudent?version=6.30.2.1093001",
             "urltype": "studentUnActiveListPage"},
            {"url": "http://yuer.szy.cn/index_7137D1D9.php", "urltype": "readingurl"},
            {"url": "https://wx.szy.cn/H5Server/service/getSchoolQrcodePage.action?",
             "urltype": "shareschoolbarcodeurl"},
            {"url": "http://a.szy.com:4480/H5Server/means/index.action?moduleNo=yd0081100",
             "urltype": "yd0081100_homeUrl"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolHuoy.jsp",
             "urltype": "schoolHuoy"},
            {"url": "http://wx.szy.cn/H5Server/view/sjinfo/sjinfo.jsp", "urltype": "h5CheckupStatisticsDetailUrl"},
            {"url": "https://wx.szy.cn/H5Server/service/getDissolutionPGropPage.action?",
             "urltype": "sharedissolutionpgroupurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumData.action", "urltype": "albumAppData"},
            {"url": "http://alpha-web.szy.com/ztjy-recruit/home", "urltype": "yd0064100_homeUrl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/schoolAlbumCompletion.action",
             "urltype": "schoolAlbumCompletion"}, {
                "url": "https://wx.szy.cn/H5Server/albumPage/shareAlbum.action?verify=7D3972FF9D8398E947ECDB357969F176&timeMillis=1602313622231",
                "urltype": "shareAlbum"},
            {"url": "http://wx.szy.cn/H5Server/icdActivity/getTeacherAct?sessionid=E81627DE292B4E8FAF3AEE7A35A39969",
             "urltype": "luckpageurl"},
            {"url": "https://wx.szy.cn/activity/showInsuranceStudent.action?", "urltype": "insuranceurl"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolUsage.jsp",
             "urltype": "schoolUsage"},
            {"url": "https://a.szy.com/CalculatorWeb/report/leader/?", "urltype": "leaderreport"},
            {"url": "https://wx.szy.cn/service/getViewPage.action?", "urltype": "detailurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageCategory.action", "urltype": "albumPageCategory"},
            {"url": "https://wx.szy.cn/H5Server/service/getSchoolInviteTchActivePage.action?",
             "urltype": "shareteacheractiveinviteurl"}, {"url": "http://www.4399er.com/erge/", "urltype": "songsurl"},
            {"url": "http://wx.szy.cn/H5Server/about/aboutus.action?", "urltype": "aboutus"},
            {"url": "https://testsecurity.ztjy61.cn/EducationServer/announcement/detail.action?",
             "urltype": "educationnoticedetail"},
            {"url": "http://wx.szy.cn/H5Server/service/getSchoolInviteStuActivePage.action?",
             "urltype": "studentactiveinviteurl"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/photoRelease.jsp",
             "urltype": "photoRelease"},
            {"url": "http://a.szy.com/MessageServer/page/detailNews.action?source=app&checksign=0&",
             "urltype": "detailnewteacher"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageStyle.action", "urltype": "albumPageStyle"},
            {"url": "http://ztjy-health-web.szy.com/temperature/collect", "urltype": "temperatureCount"},
            {"url": "http://a.szy.com/MessageServer/page/detailNotfy.action?source=app&checksign=0&",
             "urltype": "detailnotfyteacher"},
            {"url": "https://H5Server.szy.com/H5Server/rank/getFamilyRankingPage?", "urltype": "popularfamilyranking"},
            {"url": "https://H5Server.szy.com/H5Server/service/getTeacherAppTaskListPage?",
             "urltype": "teachertasklistpageurl"}, {
                "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classHuoy?signData=F05B8A506BEB5F467490C430D2A1E283",
                "urltype": "classHuoy"},
            {"url": "https://H5Server.szy.com/H5Server/growth/growthDetail?", "urltype": "growthdetail"},
            {"url": "https://wx.szy.cn/H5Server/service/getShareInviteParentForward.action?type=5",
             "urltype": "shareinviteparenturl"},
            {"url": "https://wx.szy.cn/medal/getUserMedalInfoPage.action?", "urltype": "userMedalInfo"},
            {"url": "http://dwz.cn/ztjyydnew", "urltype": "teacherdownloadurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageQuanx.action", "urltype": "albumPageQuanx"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumSpineAdd.action", "urltype": "albumSpineAdd"},
            {"url": "https://wx.szy.cn/service/getViewCoursePage.action?", "urltype": "coursesurl"},
            {"url": "http://hms.szy.com/statistics/teacherAction_index.action?", "urltype": "teacherdosagereport"},
            {"url": "http://a.szy.com/MessageServer/page/detailNotfy.action?source=app&checksign=0&isGroups=1&",
             "urltype": "detaillnotfyparent"}, {
                "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android",
                "urltype": "citydetailurl"}, {
                "url": "https://wx.szy.cn/H5Server/service/getSchoolNotifyTeacherActive.action?schoolId=vE7Z48ptN75viDCtAKX&shareUserId=0efba4b5c852401aa4f9&apptype=APP_TYPE_TEACHER",
                "urltype": "SchoolNotice"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/schoolHuoyRank.jsp",
             "urltype": "schoolHuoyRank"}, {"url": "http://www.4399er.com/gushi/", "urltype": "storyurl"},
            {"url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/contactguide.action?",
             "urltype": "contactguide"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageAdd.action", "urltype": "albumPageAdd"},
            {"url": "https://alpha-web.szy.com/ztjy-training/index", "urltype": "yd0065100_homeUrl"},
            {"url": "https://H5Server.szy.com/H5Server/security/getSecurityCheckPage.action?",
             "urltype": "securitycheckurl"},
            {"url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsDetail.action?",
             "urltype": "affairsDetail"},
            {"url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsCourse.action?",
             "urltype": "affairsCourse"}, {"url": "http://wx.szy.cn/H5Server/view/document/cancellationAgreement.jsp#",
                                           "urltype": "cancellationAccountAgreement"},
            {"url": "https://H5Server.szy.com/H5Server/pay/orderResult.action?", "urltype": "payreturnurl"},
            {"url": "https://wx.szy.cn/invite/inviteTeacherWeiXin.action?", "urltype": "inviteteacherweixinurl"},
            {"url": "https://H5Server.szy.com/H5Server/service/getTaskHelpPage?schoolId=vE7Z48ptN75viDCtAKX",
             "urltype": "scoretaskdescurl"},
            {"url": "http://ztjy-health-web.szy.com/temperature/connectHelp", "urltype": "bluetoothTemperatureGuide"}, {
                "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classDetails?signData=F05B8A506BEB5F467490C430D2A1E283",
                "urltype": "classDetails"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/rank/teacherRank.jsp",
             "urltype": "teacherRankList"},
            {"url": "https://wx.szy.cn/H5Server/service/teacherAppDown?", "urltype": "h5serverinviteurl"},
            {"url": "https://H5Server.szy.com/H5Server/service/getLevelInfoList?", "urltype": "levelinfopageurl"},
            {"url": "https://H5Server.szy.com/H5Server/security/getSecurityCheckInfoPage.action?",
             "urltype": "securitycheckdetailurl"},
            {"url": "https://H5Server.szy.com/H5Server/service/getParentAppTaskListPage?",
             "urltype": "parenttasklistpageurl"},
            {"url": "https://wx.szy.cn/H5Server/service/getSchoolInfoPage.action?", "urltype": "sharemyschoolurl"},
            {"url": "http://zthome.ztjystore.cn/BxqENL5kMMwjuTCSx93", "urltype": "growthshareurl"},
            {"url": "https://H5Server.szy.com/H5Server/rank/getPatriarchRankingPage?",
             "urltype": "popularteacherranking"},
            {"url": "http://wx.szy.cn/H5Server/means/index.action?moduleNo=yd0081100", "urltype": "means"},
            {"url": "http://alpha-web.szy.cn/edge/memberActivated/lookActivity",
             "urltype": "smileActivityForTeacherUrl"},
            {"url": "http://wx.szy.cn/H5Server/service/getSchoolInfoPage.action?", "urltype": "myschoolurl"},
            {"url": "https://zthome.ztjystore.cn/hoyeAjamHOCvOYMfndx", "urltype": "growthclassshareurl"},
            {"url": "http://a.szy.com/MessageServer/page/detailExercise.action?source=app&checksign=0&",
             "urltype": "detailexerciseteacher"},
            {"url": "https://a.szy.com/CalculatorWeb/report/teacher/?", "urltype": "teacherreport"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/listPage.action?",
             "urltype": "affichepageurl"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/getAfficheWeixin.action?",
             "urltype": "afficheweixinshare"}, {
                "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android",
                "urltype": "neardetailurl"},
            {"url": "https://wx.szy.cn/service/teacherAppDown.action?", "urltype": "inviteurl"},
            {"url": "https://a.szy.com/CalculatorWeb/report/school/?", "urltype": "schoolreport"},
            {"url": "http://wx.szy.cn/H5Server/view/sign/signPlanRemark.jsp", "urltype": "signPlanRemark"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/report/teacher/activeteacher?",
             "urltype": "teacherUnActiveListPage"}, {"url": "https://j.youzan.com/0CNrRY", "urltype": "preferredMall"},
            {"url": "https://wx.szy.cn/service/getMyScorePage.action?", "urltype": "myscorepageurl"}, {
                "url": "https://H5Server.szy.com/H5Server/service/scoreDetailPage?sessionid=E81627DE292B4E8FAF3AEE7A35A39969&teacherid=0efba4b5c852401aa4f9",
                "urltype": "scoredetaillistpageurl"},
            {"url": "https://alpha-help.szy.cn/allTheList?short_name=czjnc", "urltype": "albumSchoolPageHelpUrl"},
            {"url": "http://51110.com/mfaq", "urltype": "helpurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumPageSet.action", "urltype": "albumPageSet"},
            {"url": "https://H5Server.szy.com/H5Server/security/getDangerSourcePage.action?",
             "urltype": "dangersourceurl"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/getAfficheWeixin.action?",
             "urltype": "nearweixinshare"},
            {"url": "https://wx.szy.cn/H5Server/service/getSchoolInviteStuActivePage.action?",
             "urltype": "sharestudentactiveinviteurl"},
            {"url": "http://alpha-web.szy.cn/edge/memberActivated/gardenerActivity",
             "urltype": "smileActivityForLeaderUrl"},
            {"url": "https://wx.szy.cn/H5Server/service/getShare2SurrogateForward.action?type=4",
             "urltype": "share2Surrogate"},
            {"url": "http://alpha-web.szy.com/bflive/liveList?sessionId=E81627DE292B4E8FAF3AEE7A35A39969&t=111",
             "urltype": "liveZtjyList"}, {"url": "http://t.szy.cn/ztjyjz", "urltype": "parentdownloadurl"},
            {"url": "http://wx.szy.cn/H5Server/view/visitor/visitors/visitor_details.jsp",
             "urltype": "h5SignDetailUrl"},
            {"url": "http://a.szy.com/MessageServer/page/detailNews.action?source=app&checksign=0&",
             "urltype": "detaillnewparent"},
            {"url": "http://www.youshikoudai.com/phone/koudai/zhangtongjiayuan", "urltype": "teacherpackageurl"},
            {"url": "https://testsecurity.ztjy61.cn/SalesPromotionServer/coupon/getCouponDetail.action?",
             "urltype": "coupondetailurl"},
            {"url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/commentdetail.action?",
             "urltype": "commentdetail"},
            {"url": "http://alpha-web.szy.com/bflive/bigCoffeeList", "urltype": "liveAppointmentList"},
            {"url": "http://a.szy.com/MessageServer/page/detailExercise.action?source=app&checksign=0&isGroups=1&",
             "urltype": "detaillexerciseparent"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/listPage.action?",
             "urltype": "citypageurl"}, {"url": "http://homework.szy.com:8080/Homework", "urltype": "homeworkserver"},
            {"url": "http://a.szy.com/MessageServer/page/previewNews.action?source=app&checksign=0&",
             "urltype": "previewnewteacher"},
            {"url": "https://H5Server.szy.com/H5Server/pay/paySuccessResult.action?", "urltype": "paysuccessreturnurl"},
            {"url": "http://hms.szy.com/statistics/leaderAction_getylReport.action?", "urltype": "leaderdosagereport"},
            {"url": "https://testsecurity.ztjy61.cn/SalesPromotionServer/coupon/getCouponReceiveWeixin.action?",
             "urltype": "couponreceiveweixinurl"},
            {"url": "http://homework.szy.com:8080/Homework/page/teacher/homework/preview",
             "urltype": "homeworkpreview"},
            {"url": "https://wx.szy.cn/service/getPopularityDetailPage.action?teacherId=0efba4b5c852401aa4f9",
             "urltype": "popularitydetailpageurl"}, {
                "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/photoReleaseWeek?signData=F05B8A506BEB5F467490C430D2A1E283",
                "urltype": "photoReleaseWeek"},
            {"url": "https://wx.szy.cn/service/getViewFoodPage.action?", "urltype": "recipesurl"},
            {"url": "https://wx.szy.cn/jsp/mobile/weixin.jsp?", "urltype": "reportrepail"},
            {"url": "https://H5Server.szy.com/H5Server/rank/getGardenerRankingPage?",
             "urltype": "popularityteacherranking"},
            {"url": "http://wx.szy.cn/H5Server/temperature/getNcovCheck?", "urltype": "temperatureMeasuring"},
            {"url": "http://ztjy-sales-web.szy.com:9200/productDetail/productDetail?moduleNo=yd0064100",
             "urltype": "recruit"}, {"url": "http://a.szy.com/MessageServer/page/previewNotifyByTeacher.action?",
                                     "urltype": "previewnotifybyteacher"},
            {"url": "https://wx.szy.cn/invitation/inviteTeacherPage.action?", "urltype": "inviteteacherurl"},
            {"url": "http://wx.szy.cn/H5Server/album/schholPageEdit", "urltype": "albumSchoolPageEditUrl"},
            {"url": "https://wx.szy.cn/H5Server/register/listRegisterStudentCheckPage.action?",
             "urltype": "shareregisterstudenturl"}, {
                "url": "http://wx.szy.cn/H5Server/service/improveParentInfoList.action?source=50&methodVersion=2&schoolId=vE7Z48ptN75viDCtAKX",
                "urltype": "improveParentInfo"},
            {"url": "http://zthome.ztjystore.com/6400010120180813152156621mUk0UjOL", "urltype": "growthaudioshareurl"},
            {"url": "https://wx.szy.cn/jsp/mobile/bindCardA.jsp?", "urltype": "bindCardExplain"},
            {"url": "https://schoolaffairs.szy.com/SchoolAffairs/affairs/affairsInstructions.action?",
             "urltype": "affairsInstructions"},
            {"url": "http://wx.szy.cn/H5Server/service/getSchoolInviteTchActivePage.action?",
             "urltype": "teacheractiveinviteurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/studentAlbum.action", "urltype": "studentAlbum"},
            {"url": "http://ztjy-health-web.szy.com/temperatureGun.html", "urltype": "bluetoothTemperatureDSInterface"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/city/getAfficheWeixin.action?",
             "urltype": "cityweixinshare"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumDataV2.action", "urltype": "albumAppDataV2"},
            {"url": "https://alpha-web.szy.cn/ztjy-training/index", "urltype": "training"},
            {"url": "https://H5Server.szy.com/H5Server/publicSentiment/index?", "urltype": "publicSentiment"},
            {"url": "http://a.szy.com/MessageServer/page/previewActivity.action?source=app&checksign=0&",
             "urltype": "previewactivityteacher"},
            {"url": "https://calculatorweb.szy.com/CalculatorWeb/view/leaReportNew/classHuoyRank.jsp",
             "urltype": "classHuoyRank"},
            {"url": "http://wx.szy.cn/H5Server/service/getSchoolEnrollmentInfoPage.action?",
             "urltype": "schoolenrollmenturl"},
            {"url": "https://H5Server.szy.com/H5Server/school/reg/recommendIndex?", "urltype": "recommendurl"},
            {"url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/near/listPage.action?",
             "urltype": "nearpageurl"},
            {"url": "http://wx.szy.cn/H5Server/view/healthy/drinkWater.jsp", "urltype": "drinkWaterInfo"}, {
                "url": "https://H5Server.szy.com/H5Server/live/user/getUserLiveListPage?sessionId=E81627DE292B4E8FAF3AEE7A35A39969",
                "urltype": "liveList"},
            {"url": "http://wx.szy.cn/H5Server/view/album/knowMore.jsp", "urltype": "albumKnowMore"},
            {"url": "http://alpha-web.szy.com/ztjy-recruit/website/share?", "urltype": "newMySchoolUrl"},
            {"url": "https://wx.szy.cn/H5Server/service/getClassQrcodePage.action?", "urltype": "shareclassbarcodeurl"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/studentAlbumV2.action", "urltype": "studentAlbumV2"},
            {"url": "http://ztjy-health-web.szy.com/temperature/record", "urltype": "temperatureHistory"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/classAlbumPage.action", "urltype": "classAlbum"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/publishAlbum.action", "urltype": "publishAlbum"}, {
                "url": "https://testsecurity.ztjy61.cn/ScoreServer/score/getParentExpTaskListPage.action?sessionid=E81627DE292B4E8FAF3AEE7A35A39969",
                "urltype": "parentexptasklisturl"},
            {"url": "http://wx.szy.cn/H5Server/service/getDissolutionPGropPage.action?",
             "urltype": "dissolutionpgroupurl"}, {
                "url": "http://testsecurity.ztjy61.cn/AfficheServer/affiche/detailAffiche.action?userId=0efba4b5c852401aa4f9&appType=APP_TYPE_TEACHER&devType=Android",
                "urltype": "affichedetai"}, {
                "url": "https://wx.szy.cn/CalculatorWeb/report/teacher/classDetailsVs?signData=F05B8A506BEB5F467490C430D2A1E283",
                "urltype": "classDetailsVs"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/classAlbumPageV2.action", "urltype": "classAlbumV2"},
            {"url": "http://wx.szy.cn/H5Server/albumPage/albumGuide.action", "urltype": "albumGuide"},
            {"url": "http://a.szy.com/MessageServer/page/weiXinMsg.action?", "urltype": "weixin_msg"},
            {"url": "https://wx.szy.cn/H5Server/food/getInfoPage?", "urltype": "shareFoodInfo"},
            {"url": "http://wx.szy.cn/wxShareDownload?", "urltype": "shareinformlurl"}], "rongappkey": ""},
               "message": "成功", "returncode": "10000"}

    cmp('urltype','url',params1,params2)
    print('*'*10)
    cmp('urltype','url',params2,params1)

